[unix_http_server]
file=/config/.local/state/chatgpt/supervisor.sock
chmod=0600
[supervisord]
logfile=/config/.local/state/chatgpt/supervisor.log
pidfile=/config/.local/state/chatgpt/supervisor.pid
childlogdir=/config/.local/state/chatgpt
[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface
[supervisorctl]
serverurl=unix:///config/.local/state/chatgpt/supervisor.sock
[include]
files=/config/.config/supervisor/*.conf
