creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - age1d63le0ru5vd4dh98kpsfy03ygkwya4sdz6dwge4rw6flg022ug5qd0fgg6 # armored-armadillo
          - age1whdrlhw24r0ucgttfcvvrkmpchswfya5dmu79zvmfzyhdwdqks3sjj2uhy # chill-penguin
          - age1kfz4asnfhjpr97xd5dg6zkus3hgfxth5pesq8zlvcs59qguhpp0s398w8l # launch-octopus
