# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and then manually optimized for Btrfs and Apple Silicon (M1 Ultra).
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" "usb_storage" "sdhci_pci" "nvme_apple" "apple_mailbox" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e6cdd1d0-be9b-4519-80a2-822212367dd6";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e6cdd1d0-be9b-4519-80a2-822212367dd6";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e6cdd1d0-be9b-4519-80a2-822212367dd6";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/e6cdd1d0-be9b-4519-80a2-822212367dd6";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3E8C-1D0C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/share" =
    { device = "192.168.200.106:/volume1/share";
      fsType = "nfs";
      options = [ "nofail" "x-systemd.automount" "noatime" "nodiratime" "soft" "intr" "timeo=30" "retrans=2" "rsize=1048576" "wsize=1048576" "nfsvers=4.1" "async" "tcp" "actimeo=120" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
